baseURL = "https://akhy.chickenzord.com/"
theme = "minimo"
title = "chicken.write(blog)"
description = "why did the chicken writes a blog?"
canonifyurls = true
defaultContentLanguage = "en"
googleAnalytics = "UA-117694463-1"
enableRobotsTXT = true
pygmentsCodefences = true
enableEmoji = true


# BLOG CORE

[params.info]
description = "why did the chicken writes a blog?"

[taxonomies]
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
identifier = "home"
url = "/"
weight = -999

[[menu.main]]
name = "Posts"
identifier = "posts"
url = "/posts/"

[params.assets]
favicon = "img/rooster.svg"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]

[params.settings]
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "Jan 02"
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#00cdff"


# SIDEBAR and WIDGETS
[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]
footer = ["social_menu"]

[params.copyright]
prefix = ""
holder = "akhy"
startYear = "2018"
suffix = ""

# SOCIAL

[params.social]
github = "akhy"
linkedin = "akhyar"
twitter = "akhy"

[params.opengraph.twitter]
page = "akhy"


# TRANSLATIONS

[languages.en]
[languages.id]
