baseURL = "https://akhy.chickenzord.com/"
theme = "cocoa"
title = "a chicken writes blog"
description = "why did the chicken writes a blog?"
canonifyurls = true
defaultContentLanguage = "en"
languageCode = "en-us"
googleAnalytics = "UA-117694463-1"

[[menu.main]]
name = "About"
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Posts"
identifier = "blog"
url = "/blog/"

[params]
include_rss            = true
i18n_flags             = true
faviconfile            = "img/rooster.svg"
avatar                 = "img/rooster.svg"
author                 = "akhy"
selfintro              = "a chicken writes blog"
description            = "why did the chicken writes a blog?"
github                 = "//github.com/akhy"
linkedin               = "//linkedin.com/in/akhyar"
twitter                = "//twitter.com/akhy"
mastodon               = "//mastodon.social/@akhy"
cachebuster            = true
highlightjs            = true
extracssfiles          = [ "/css/override.css" ]

[languages.en]
[languages.id]
title = "seekor ayam menulis blog"
description = "kenapa ayam menulis blog?"
[languages.id.params]
selfintro = "seekor ayam menulis blog"
description = "kenapa ayam menulis blog?"
